config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'orders#index'
  end

  root 'pages#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, only: [:show, :update] do
    collection do
      post :sms_verify
      get :sms_verify_form
      post :send_sms_code
      get :reset_password_form
      post :reset_password
    end
    member do
      post :check_phone
    end
  end
  resources :cars, only: [:create, :edit, :update, :destroy, :show]
  resources :bids, only: [:new, :create]

  get :my_profile, to: 'users#show'
  scope 'my_profile' do
    get :edit, to: 'users#edit'
    get :add_car, to: 'cars#new'
  end

  resources :orders, except: [:edit, :update] do
    collection do
      get :my
    end
    resources :comments
    resources :offers, only: :create
    member do
      post :close
      post :complete
    end
  end
  resources :offers do
    member do
      post :accept
      post :reject
    end
  end
  resources :documents

  namespace :admin do
    root 'users#index'

    resources :bids do
      collection do
        get :search_results
      end
      member do
        get :close
      end
    end

    resources :users do
      collection do
        get :inactive
        get :search_results
      end
      member do
        post :activate
        post :deactivate
        get :show_docs
      end
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  mount_uploader :image, DocumentUploader

  validates :title, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  def new
    authorize! :create, @document
    @document = Document.new
  end

  def create
    authorize! :create, @document
    @document = current_user.documents.create(document_params)
    if @document.save
      redirect_to documents_path
    else
      flash[:danger] = 'something wrong'
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = Document.find(params[:id])
    @document.update(document_params)
    redirect_to documents_path
  end

  def show
    @document = Document.find(params[:id])
  end

  def index
    @documents = current_user.documents
  end

  private
  def document_params
    params.require(:document).permit(:title, :image)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for @document do |f| %>
  <%= f.input :title %>
  <%= f.input :image, as: :file %>
  <%= f.submit %>
<% end %>

app/views/documents/edit.html.erb
<div class="col-md-9 toppad">
	<%= render 'form' %>
</div>

app/views/documents/index.html.erb
<div class="col-md-10 toppad">
  <table class="table table-striped custab">
    <thead>
    <%= link_to '+Добавить документ', new_document_path, class: 'btn btn-primary btn-xs pull-right' %>
    <tr>
      <th>Название</th>
      <th>Изображение</th>
      <th class="text-center">Действие</th>
    </tr>
    </thead>
  <% @documents.each do |doc| %>
        <tr>
          <td><%= doc.title %> </td>
          <td><%= link_to (image_tag doc.image.thumb), document_path(doc) %></td>
          <td class="text-center">
            <%= link_to '<i class="glyphicon glyphicon-edit"></i> Редактировать'.html_safe, edit_document_path(doc), class: 'btn btn-info btn-xs' %>
          </td>
        </tr>
  <% end %>
  </table>
</div>

app/views/documents/new.html.erb
<div class="col-md-9 toppad">
	<%= render 'form' %>
</div>

app/views/documents/show.html.erb
<%= image_tag @document.image %>