config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'orders#index'
  end

  root 'pages#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, only: [:show, :update] do
    collection do
      post :sms_verify
      get :sms_verify_form
      post :send_sms_code
      get :reset_password_form
      post :reset_password
    end
    member do
      post :check_phone
    end
  end
  resources :cars, only: [:create, :edit, :update, :destroy, :show]
  resources :bids, only: [:new, :create]

  get :my_profile, to: 'users#show'
  scope 'my_profile' do
    get :edit, to: 'users#edit'
    get :add_car, to: 'cars#new'
  end

  resources :orders, except: [:edit, :update] do
    collection do
      get :my
    end
    resources :comments
    resources :offers, only: :create
    member do
      post :close
      post :complete
    end
  end
  resources :offers do
    member do
      post :accept
      post :reject
    end
  end
  resources :documents

  namespace :admin do
    root 'users#index'

    resources :bids do
      collection do
        get :search_results
      end
      member do
        get :close
      end
    end

    resources :users do
      collection do
        get :inactive
        get :search_results
      end
      member do
        post :activate
        post :deactivate
        get :show_docs
      end
    end
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :order

  validates :about, presence: true

  def accept
    self.accepted = true
    save
  end

  def reject
    self.accepted = false
    save
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def create
    @order = Order.find(params[:order_id])
    authorize! :offer, @order
  	@offer = Offer.new(offer_params)
    @offer.user = current_user
    @offer.order = @order
    @offer.status = 'new'
  	if @offer.save
      redirect_back(fallback_location: root_path)
  	else
  		redirect_to root_path
  	end
  end

  def edit
    authorize! :update, @offer
    @offer = Offer.find(params[:id])
  end

  def update
    authorize! :update, @offer
    @offer = Offer.find(params[:id])
    @offer.update(offer_params) if @offer.user == current_user
    redirect_to order_path(@offer.order)
  end

  def destroy
    authorize! :destroy, @offer
    @offer = Offer.find(params[:id])
    @offer.destroy if @offer.user == current_user
    redirect_back(fallback_location: root_path)
  end

  def accept
    authorize! :accept, @offer
    @offer = Offer.find(params[:id])
    @order = @offer.order
    @offer.accept
    @order.in_progress
    @order.update(worker: @offer.user)
    redirect_back(fallback_location: root_path)
  end

  def reject
    authorize! :reject, @offer
    @offer = Offer.find(params[:id])
    @order = @offer.order
    @offer.reject
    @order.open
    @order.update(worker: nil)
    redirect_back(fallback_location: root_path)
  end

  private

  def offer_params
    params.require(:offer).permit(:status, :about, :user_id, :order_id)
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= simple_form_for [@order, @offer] do |f| %>
    <div class="form-group">
      <%= f.input :about, label: false %>
    </div>
    <div class="form-group">
      <%= f.submit "Предложить", class: "btn btn-primary btn-block btn-lg", id: 'create_offer' %>
    </div>
<% end %>

app/views/offers/_offer.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-header">
    </div>
    <div class="comments-list">
      <div class="media">
        <p class="pull-right">
          <small><%= offer.created_at.strftime("%Y-%m-%d") %></small>
        </p>
        <a class="media-left" href="#">
          <%= image_tag offer.user.avatar.url(:avatarka), size: '40x40' %>
        </a>
        <div class="media-body">

          <h4 class="media-heading user_name"><%= link_to offer.user.name, user_path(offer.user) %></h4>
          <%= offer.about %>
          <p>
            <small>
              <%= link_to 'Удалить', offer_path(offer), id: 'delete_offer', method: 'delete' if can? :destroy, offer %>
              <%= link_to 'Изменить', edit_offer_path(offer), id: 'change_offer_price' if can? :update, offer %>
              <% unless offer.accepted %>
                  <%= link_to 'Принять', accept_offer_path(offer), class: "btn btn-success", method: :post if can? :accept, offer %>
                  <% else %>
              <%= link_to 'Расторгнуть!', reject_offer_path(offer), class: "btn btn-danger", method: :post if can? :reject, offer %>
                  <% end %>                  
            </small>
            <h3><span class="label label-default"><%= offer.user.phone if offer.accepted?%></span></h3>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
  

app/views/offers/edit.html.erb
<div class="container">
  <h3>Измените предложенную цену:</h3>
  <%= render 'form' %>
</div>