config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'orders#index'
  end

  root 'pages#index'

  devise_for :users, :controllers => {registrations: 'registrations'}
  resources :users, only: [:show, :update] do
    collection do
      post :sms_verify
      get :sms_verify_form
      post :send_sms_code
      get :reset_password_form
      post :reset_password
    end
    member do
      post :check_phone
    end
  end
  resources :cars, only: [:create, :edit, :update, :destroy, :show]
  resources :bids, only: [:new, :create]

  get :my_profile, to: 'users#show'
  scope 'my_profile' do
    get :edit, to: 'users#edit'
    get :add_car, to: 'cars#new'
  end

  resources :orders, except: [:edit, :update] do
    collection do
      get :my
    end
    resources :comments
    resources :offers, only: :create
    member do
      post :close
      post :complete
    end
  end
  resources :offers do
    member do
      post :accept
      post :reject
    end
  end
  resources :documents

  namespace :admin do
    root 'users#index'

    resources :bids do
      collection do
        get :search_results
      end
      member do
        get :close
      end
    end

    resources :users do
      collection do
        get :inactive
        get :search_results
      end
      member do
        post :activate
        post :deactivate
        get :show_docs
      end
    end
  end
end

app/views/layouts/_customer_menu.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
        	<%= link_to root_path do %>
					  <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-road"></span>МОИ ЗАКАЗЫ
					<% end %>
        </li>
        <li class="active">
          <% if can? :create, Order  %>
            <%= link_to new_order_path do %>
              <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span>НОВЫЙ ЗАКАЗ
            <% end %>
          <% end %>
        </li>
        <li class="active">
          <%= link_to new_bid_path, id: 'new_bid' do %>
              <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-stats"></span>РАССЧИТАТЬ СТОИМОСТЬ
          <% end %>
        </li>
        <li class="active">
        	<%= link_to my_profile_path, id: 'my_profile' do %>
					  <span style="font-size:16px;" class="pull-right hidden-xs showopacity ic-user glyphicon glyphicon-user"></span>МОИ ПРОФИЛЬ
					<% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
 

app/views/layouts/_worker_menu.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to root_path do %>
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-road"></span>ВСЕ ЗАКАЗЫ
          <% end %>
        </li>
        <li class="active">
          <%= link_to my_orders_path, id: 'my_orders' do %>
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-th-list"></span>МОИ ЗАКАЗЫ
          <% end %>
        </li>
        <li class="active">
          <%= link_to my_profile_path, id: 'my_profile' do %>
            <span style="font-size:16px;" class="pull-right hidden-xs showopacity ic-user glyphicon glyphicon-user"></span>МОЙ ПРОФИЛЬ
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trucking</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/admin/navbar' %>

<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trucking</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyC1LhL0Z7BctFQqK6k1wLHAl9easzDh1Ks"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
</head>

<body>
<div class="content">
  <div class="container">
    <%= render 'layouts/application/navbar' %>

    <% flash.each do |type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{type}" %>
    <% end %>

    <% if user_signed_in? %>
        <% if current_user.customer? %>
            <%= render 'layouts/customer_menu' %>
        <% elsif current_user.worker? %>
            <%= render 'layouts/worker_menu' %>
        <% end %>

        <% if current_user.profile_uncomplete? and current_user.phone_checked? %>
            <%= render 'layouts/application/complete_your_profile' %>
        <% else %>
            <% if !current_user.profile_uncomplete? and current_user.inactive_worker? %>
                <div class="alert alert-info">
                  <h3>Вы заполнили все необходимые поля.</h3>
                  В ближайшее время администратор проверит ваши данные и активирует
                  вас.
                  Вы получите доступ к заказам после активизации!
                </div>
            <% end %>
        <% end %>

        <%= render 'layouts/application/phone_number_confirm' unless current_user.phone_checked? %>

    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trucking</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= yield %>

</body>
</html>